#define IDLE_STATE 0
#define ANGRY_STATE 1
#define IN_LOVE_STATE 2
#define HAPPY_STATE 3
#define DEAD_STATE 4
#define WAKING_UP_STATE 5
#define FALLING_ASLEEP_STATE 6
#define SEARCHING_WIFI_STATE 7
#define SHITTY_FLUTE_TIME_STATE 8

#define TEST_STATE 666